CREATE TABLE oracle_elixir_2025(
	seq bigint primary key auto_increment,
    gameid VARCHAR(100),
    datacompleteness VARCHAR(50),
    url VARCHAR(255),
    league VARCHAR(50),
    game_year INT,
    split VARCHAR(50),
    playoffs BOOLEAN,
    game_date DATETIME,
    game INT,
    patch decimal(4,2),
    participantid INT,
    side VARCHAR(10),
    position VARCHAR(20),
    playername VARCHAR(100),
    playerid VARCHAR(100),
    teamname VARCHAR(100),
    teamid VARCHAR(100),
    name_us VARCHAR(50),
    ban1 VARCHAR(50),
    ban2 VARCHAR(50),
    ban3 VARCHAR(50),
    ban4 VARCHAR(50),
    ban5 VARCHAR(50),
    pick1 VARCHAR(50),
    pick2 VARCHAR(50),
    pick3 VARCHAR(50),
    pick4 VARCHAR(50),
    pick5 VARCHAR(50),
    gamelength INT,
    result BOOLEAN,
    kills INT,
    deaths INT,
    assists INT,
    teamkills INT,
    teamdeaths INT,
    doublekills INT,
    triplekills INT,
    quadrakills INT,
    pentakills INT,
    firstblood BOOLEAN,
    firstbloodkill BOOLEAN,
    firstbloodassist BOOLEAN,
    firstbloodvictim BOOLEAN,
    team_kpm float,
    ckpm float,
    firstdragon BOOLEAN,
    dragons INT,
    opp_dragons INT,
    elementaldrakes INT,
    opp_elementaldrakes INT,
    infernals INT,
    mountains INT,
    clouds INT,
    oceans INT,
    chemtechs INT,
    hextechs INT,
    dragons_type_unknown INT,
    elders INT,
    opp_elders INT,
    firstherald BOOLEAN,
    heralds INT,
    opp_heralds INT,
    void_grubs INT,
    opp_void_grubs INT,
    firstbaron BOOLEAN,
    barons INT,
    opp_barons INT,
    firsttower BOOLEAN,
    towers INT,
    opp_towers INT,
    firstmidtower BOOLEAN,
    firsttothreetowers BOOLEAN,
    turretplates INT,
    opp_turretplates INT,
    inhibitors INT,
    opp_inhibitors INT,
    damagetochampions INT,
    dpm FLOAT,
    damageshare FLOAT,
    damagetakenperminute FLOAT,
    damagemitigatedperminute FLOAT,
    wardsplaced INT,
    wpm FLOAT,
    wardskilled INT,
    wcpm FLOAT,
    controlwardsbought INT,
    visionscore INT,
    vspm FLOAT,
    totalgold INT,
    earnedgold INT,
    earned_gpm FLOAT,
    earnedgoldshare FLOAT,
    goldspent INT,
    gspd FLOAT,
    gpr FLOAT,
    total_cs INT,
    minionkills INT,
    monsterkills INT,
    monsterkillsownjungle INT,
    monsterkillsenemyjungle INT,
    cspm FLOAT,
    goldat10 INT,
    xpat10 INT,
    csat10 INT,
    opp_goldat10 INT,
    opp_xpat10 INT,
    opp_csat10 INT,
    golddiffat10 INT,
    xpdiffat10 INT,
    csdiffat10 INT,
    killsat10 INT,
    assistsat10 INT,
    deathsat10 INT,
    opp_killsat10 INT,
    opp_assistsat10 INT,
    opp_deathsat10 INT,
    goldat15 INT,
    xpat15 INT,
    csat15 INT,
    opp_goldat15 INT,
    opp_xpat15 INT,
    opp_csat15 INT,
    golddiffat15 INT,
    xpdiffat15 INT,
    csdiffat15 INT,
    killsat15 INT,
    assistsat15 INT,
    deathsat15 INT,
    opp_killsat15 INT,
    opp_assistsat15 INT,
    opp_deathsat15 INT,
    goldat20 INT,
    xpat20 INT,
    csat20 INT,
    opp_goldat20 INT,
    opp_xpat20 INT,
    opp_csat20 INT,
    golddiffat20 INT,
    xpdiffat20 INT,
    csdiffat20 INT,
    killsat20 INT,
    assistsat20 INT,
    deathsat20 INT,
    opp_killsat20 INT,
    opp_assistsat20 INT,
    opp_deathsat20 INT,
    goldat25 INT,
    xpat25 INT,
    csat25 INT,
    opp_goldat25 INT,
    opp_xpat25 INT,
    opp_csat25 INT,
    golddiffat25 INT,
    xpdiffat25 INT,
    csdiffat25 INT,
    killsat25 INT,
    assistsat25 INT,
    deathsat25 INT,
    opp_killsat25 INT,
    opp_assistsat25 INT,
    opp_deathsat25 INT
);
alter table oracle_elixir modify column patch decimal(4,2); 
drop table oracle_elixir;
select patch from oracle_elixir;
select count(*) from oracle_elixir where patch = '14.23';
select count(*) from oracle_elixir where patch=14.23 and participantid = 100;
select * from oracle_elixir where Date(game_date) = "2024-08-24";
select * from oracle_elixir where gameid = "LOLTMNT02_157559";
use lol_dev;
select * from oracle_elixir_2025;
SELECT 
    o.gameid,
    o.position,
    o.champion,
    o.playername,
    o.teamname,
    o.patch,
    p.performance_score,
    p.win_rate,
    p.pick_rate,
    p.is_outlier
FROM oracle_elixir o
JOIN performance_score p 
    ON o.position = p.line
    and p.name_us = o.champion
    and p.patch = o.patch
WHERE p.is_outlier = true
    AND o.position != 'team'
    and o.patch = 14.23
ORDER BY o.gameid, o.position;

select * from performance_score where is_outlier = true and patch = 14.23 and line = "mid";

